### ISSUE TITLE
POC: create md drivers

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#14]
- [x] stfc/janus-core#15
- [x] stfc/janus-core#16
- [x] stfc/janus-core#17
- [x] stfc/janus-core#18

**Comment by alinelena** [comment]
done in #87
